# Generated by Django 4.2.13 on 2026-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_status',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('enrolled', 'Enrolled')], default='applicant', max_length=20),
        ),
    ]
