# Generated by Django 4.2.13 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
