# Generated by Django 4.2.13 on 2026-02-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_application_student_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_id_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_recommendation_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_transcript_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='issued_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
