# Generated by Django 4.2.13 on 2026-02-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_application_flow_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                (
                    "office_code",
                    models.CharField(
                        choices=[
                            ("ARG", "Office of the Registrar"),
                            ("FIN", "Finance, Bursar & Procurement Office"),
                            ("HRM", "Human Resources (HR)"),
                            ("ACA", "Academic Affairs / Provost Office"),
                            ("ADM", "Admissions and Student Services Office"),
                            ("ELE", "E-Learning and Digital Education Office"),
                            ("LIB", "University Library Services"),
                        ],
                        max_length=3,
                    ),
                ),
                ("issue_year", models.PositiveIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("full_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["office_code", "issue_year"], name="dashboard_s_office__87f593_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office_code", "issue_year", "sequence"),
                        name="uniq_staff_sequence_per_office_year",
                    )
                ],
            },
        ),
    ]
