# Generated by Django 4.2.13 on 2026-02-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_staffprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="assigned_password",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

