# Generated by Django 6.0.2 on 2026-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_academicmodule_academicsession_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
